name: Check Product Availability

on:
  schedule:
    - cron: "*/5 * * * *"  # co 15 minut
  workflow_dispatch:        # ręczne uruchamianie

jobs:
  run-check:
    runs-on: ubuntu-latest

    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
      TO_PHONE_NUMBER: ${{ secrets.TO_PHONE_NUMBER }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Run script
        run: python main.py
