name: Check Product Availability

on:
  schedule:
    - cron: "*/6 * * * *"  
  workflow_dispatch:      
  
permissions:
  contents: write
  
jobs:
  run-check:
    runs-on: ubuntu-latest

    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
      TO_PHONE_NUMBER: ${{ secrets.TO_PHONE_NUMBER }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps
      
      - name: 🚀 Run script
        run: python main.py

      - name: 📤 Commit updated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash

          git add notified.json price_history.csv

          git diff --cached --quiet && echo "✅ Brak zmian do commitowania." || (
            git commit -m "🔄 Update notified.json + 📈 price history [skip ci]"
            git push
          )
